version: 2

builds:
  - id: "upx"
    main: ./cmd/hashimg
    binary: hashimg
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    gcflags:
      - "all=-B -l=120"
    ldflags:
      - -s -w -X github.com/jaeiya/hashimg/internal.AppVersion={{ .Tag }}
    goarch:
      - amd64
    goamd64:
      - v2
    hooks:
      post: # Hook to run after the build
        - upx --best --lzma -qq --force-overwrite --force-macos {{ .Path }}

  - id: "no-upx"
    main: ./cmd/hashimg
    binary: hashimg
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    gcflags:
      - "all=-B -l=120"
    ldflags:
      - -s -w -X github.com/jaeiya/hashimg/internal.AppVersion={{ .Tag }}
    goarch:
      - arm64

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^tdd"
      - "^test"
  groups:
    - title: New
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100

    - title: Changes
      regexp: "^.*upd[(\\w)]*:+.*$"
      order: 200

    - title: "Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 300

    - title: "Docs"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400

    - title: "Cleaning"
      regexp: "^.*clean[(\\w)]*:+.*$"
      order: 500

    - title: "Maintenance"
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 600

    - title: "Testing"
      regexp: "^.*tdd[(\\w)]*:+.*$"
      order: 700

    - title: "Other"
      order: 999

archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
