version: 2

builds:
  - main: ./cmd/hashimg
    binary: hashimg
    flags:
      - -trimpath
    gcflags:
      - "all=-B -l=120"
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goamd64:
      - v2
      - v3

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^tdd"
      - "^test"
  groups:
    - title: New
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100

    - title: Changes
      regexp: "^.*upd[(\\w)]*:+.*$"
      order: 200

    - title: "Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 300

    - title: "Docs"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400

    - title: "Cleaning"
      regexp: "^.*clean[(\\w)]*:+.*$"
      order: 500

    - title: "Maintenance"
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 600

    - title: "Other"
      order: 999

archives:
  - format_overrides:
      - goos: windows
        format: zip

universal_binaries:
  - replace: true
