version: 2

builds:
  - main: ./cmd/hashimg
    binary: hashimg
    flags:
      - -trimpath
    gcflags:
      - "all=-B -l=120"
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goamd64:
      - v2
      - v3

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^tdd"
      - "^test"
  groups:
    - title: New
      regexp: "^feat:.+$|^feat\\(.+\\):.+$"
      order: 100
    - title: "Fixes"
      regexp: "^fix:.+$|^fix\\(.+\\):.+$"
      order: 200
    - title: "Docs"
      regexp: "^docs:.+$|^docs\\(.+\\):.+$"
      order: 300
    - title: "Maintenance"
      regexp: "^clean:.+$|^clean\\(.+\\):.+$|^chore:.+$|^chore\\(.+\\):.+$"
      order: 400
    - title: "Changes"
      order: 999

archives:
  - format_overrides:
      - goos: windows
        format: zip

universal_binaries:
  - replace: true
