version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: "upx"
    main: ./cmd/hashimg
    binary: >-
      {{- if .IsSnapshot }}hashimg_{{ .ShortCommit }}
      {{- else }}hashimg_{{ .Tag }}_{{ .Os }}_
      {{- if (eq .Arch "amd64") }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- end }}
      {{- if not (eq .Amd64 "v2") }}_{{ .Amd64 }}{{ end }}
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    gcflags:
      - "all=-B -l=120"
    ldflags:
      - -s -w
      - -X github.com/jaeiya/hashimg/internal.appVersion={{ .Tag }}
      - -X github.com/jaeiya/hashimg/internal.commitSha={{ .ShortCommit }}
    goarch:
      - amd64
    goamd64:
      - v2
      - v3
    ignore:
      - goos: windows
    hooks:
      post: # Hook to run after the build
        - upx --best --lzma -qq --force-overwrite --force-macos {{ .Path }}

  - id: "upx-windows"
    main: ./cmd/hashimg
    binary: >-
      {{- if .IsSnapshot }}hashimg_{{ .ShortCommit }}
      {{- else }}hashimg_{{ .Tag }}_{{ .Os }}_
      {{- if (eq .Arch "amd64") }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- end }}
      {{- if not (eq .Amd64 "v2") }}_{{ .Amd64 }}{{ end }}
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    gcflags:
      - "all=-B -l=120"
    ldflags:
      - -s -w
      - -X github.com/jaeiya/hashimg/internal.appVersion={{ .Version }}
      - -X github.com/jaeiya/hashimg/internal.commitSha={{ .ShortCommit }}
    goarch:
      - amd64
    goamd64:
      - v2
      - v3
    ignore:
      - goos: linux
      - goos: darwin
    hooks:
      post: # Hook to run after the build
        - upx --best --lzma -qq --force-overwrite {{ .Path }}
    no_unique_dist_dir: true

  - id: "no-upx"
    main: ./cmd/hashimg
    binary: hashimg
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    gcflags:
      - "all=-B -l=120"
    ldflags:
      - -s -w
      - -X github.com/jaeiya/hashimg/internal.appVersion={{ .Tag }}
      - -X github.com/jaeiya/hashimg/internal.commitSha={{ .ShortCommit }}
    goarch:
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm64

snapshot:
  version_template: "#{{ .ShortCommit }}"

archives:
  - id: unix
    name_template: >-
      hashimg_{{ .Tag }}_{{ .Os }}_
      {{- if (eq .Arch "amd64") }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if not (eq .Amd64 "v2") }}_{{ .Amd64 }}{{ end }}
    builds:
      - no-upx
      - upx

  - id: windows
    builds:
      - upx-windows
    format: binary
    files:
      - none*
    wrap_in_directory: false
    strip_binary_directory: true

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^tdd"
      - "^test"
  groups:
    - title: New
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100

    - title: Changes
      regexp: "^.*upd[(\\w)]*:+.*$"
      order: 200

    - title: "Fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 300

    - title: "Docs"
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400

    - title: "Cleaning"
      regexp: "^.*clean[(\\w)]*:+.*$"
      order: 500

    - title: "Maintenance"
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 600

    - title: "Testing"
      regexp: "^.*tdd[(\\w)]*:+.*$"
      order: 700

    - title: "Other"
      order: 999
