name: ci
on:
  push:
    branches:
      - dev
  pull_request:

permissions:
  contents: read
  actions: read
  checks: write
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x

      - name: Install Gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests with gotestsum and generate JUnit report
        run: gotestsum --junitfile test-results.xml

      - name: Publish Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: "./test-results.xml"

  golanglint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
          install-mode: "goinstall"
